language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer install

script: 
  - phpunit --configuration phpunit.xml